### ISSUE TITLE
Cannot get sample building in my own project

### ISSUE THREAD

**Issue by radman5** [Azure-Samples/active-directory-dotnet-graphapi-web#18]
I have copied over the files that are mentioned in the steps but even those classes rely on others in the sample project so I had to copy over pretty much everything and now that that is done my GraphClient.Constants does not have the definition for ResourceUrl or TenantId that are referenced in the AuthenticationHelper class.

Does anyone know how I can get this resolved??

Thank you!

**Comment by nitinmeria** [comment]
Have you tried running the sample itself?

**Comment by dkershaw10** [comment]
@radman5 this doesn't look like an issue with the library itself.  Have you managed to resolve your issue?

**Comment by radman5** [comment]
@dkershaw10 Yes all issues resolved. I don't remember the solution because I can't even remember posting this. 

Sorry for the trouble.
