### ISSUE TITLE
Cannot resolve symbol ActiveDirectoryClient

### ISSUE THREAD

**Issue by hvaughan3** [Azure-Samples/active-directory-dotnet-graphapi-web#19]
After creating the `AuthenticationHelper.cs` file, I was getting the error below and was unable to build the project. I did not find anyone else talking about this issue so I went ahead and just tried updating the `Microsoft.Azure.ActiveDirectory.GraphClient` package and that seems to have fixed the problem.

Error:
`Cannot resolve symbol ActiveDirectoryClient`

My Info:
Windows 7 x64
Visual Studio 2013
.NET Framework 4.5

If this is indeed the correct way to fix the issue, then the part in the README that tells you to install version 1.0.3, should be changed. Thank you.

**Comment by dkershaw10** [comment]
We'll update the readme to remove the specific version.
