### ISSUE TITLE
{"odata.error":{"code":"Request_BadRequest","message":{"lang":"en","value":"Property  value is required but is empty or missing."},"values":null}}

### ISSUE THREAD

**Issue by levalencia** [Azure-Samples/active-directory-dotnet-graphapi-web#27]
I am using this sample but creating users does not work, apparently we are missing a property to be set but my code is a copy paste from this sample

http://stackoverflow.com/questions/31565446/error-when-creating-d-auser-odata-errorcoderequest-badrequest

**Comment by dkershaw10** [comment]
Looks like this issue was resolved.  We are working on better error messages that should help next time.

**Comment by ravishankar1730** [comment]
You missed the property "AccountEnabled" .
