### ISSUE TITLE
System OutOfMemory Exception thrown in GroupsController

### ISSUE THREAD

**Issue by yfan183** [Azure-Samples/active-directory-dotnet-graphapi-web#51]
When I try to use the getmembers method, I get a outofmemory exception on the line users.Add((User) directoryObject); I'm not sure what caused this as I had plenty of RAM available

**Comment by VitorX** [comment]
Are you able to reproduce this issue on other machine with same request?

**Comment by yfan183** [comment]
Don't worry. I managed to resolve this issue.
