### ISSUE TITLE
Users mail and otheremails always null or empty

### ISSUE THREAD

**Issue by danpardo** [Azure-Samples/active-directory-dotnet-graphapi-web#53]
Hey, I am using graph api to perform operations on the company AD B2C tenant, and when I get the list of users, the user mail or othermails properties are null or empty, but in the token claims I can get the user mail without any problem. Any idea why I can't get mail information using graph api?

**Comment by gsacavdm** [comment]
Hey @danpardo, emails in Azure AD B2C are a bit tricky.
* For locals accounts created via a signup or unified signup/signin policy - the email will be in the signInNames array.
* For social accounts created via a signup or unified signup/signin policy - the email will be in the otherMails array.
* For accounts created via the Azure portal directly, those won't have an email. You shouldn't be creating accounts that way anyway.

I'm closing this issue as this isn't an issue in the sample itself but rather a more open ended question. Follow up questions on this should be asked on StackOverflow (along with appropriate code snippets) with the [azure-ad-b2c tag](http://stackoverflow.com/questions/tagged/azure-ad-b2c)
