### ISSUE TITLE
got exception "authorization required" and "invalid request url"

### ISSUE THREAD

**Issue by renjiezhang** [Azure-Samples/active-directory-dotnet-graphapi-web#60]
I have done all of the configurations followed by the instruction. However, I still got the exceptions when running the sample code under VS2015. It still keep asking me to re-login in when I was ready logged in.

**Comment by renjiezhang** [comment]
![capture](https://user-images.githubusercontent.com/6053772/30613335-a1b99a88-9d55-11e7-9824-514ff2e8e3d0.JPG)

**Comment by renjiezhang** [comment]
i have solved the problem

**Comment by Niahm** [comment]
please tell us how.
